name: Rcpp Gallery
description: Articles and code that provide examples of using the Rcpp package
repo: https://github.com/RcppCore/rcpp-gallery

url: http://gallery.rcpp.org
permalink: "articles/:title"

exclude: 
  - COPYING
  - README.md 
  - Makefile
  - src
  - figure

highlighter: pygments

markdown: kramdown



